class AuditAction:
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_DELETED = "USER_DELETED"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"

    FILE_UPLOADED = "FILE_UPLOADED"
    FILE_DOWNLOADED = "FILE_DOWNLOADED"
    FILE_DELETED = "FILE_DELETED"

    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    DUPLICATE_GROUP_CREATED = "DUPLICATE_GROUP_CREATED"
    DUPLICATE_GROUP_UPDATED = "DUPLICATE_GROUP_UPDATED"

    FILE_PROTECTED = "FILE_PROTECTED"
    FILE_UNPROTECTED = "FILE_UNPROTECTED"


class AuditEntity:
    USER = "USER"
    FILE = "FILE"
    DUPLICATE_GROUP = "DUPLICATE_GROUP"
